version: '2'
networks:
  lb_web:
    external: true
services:
  web:
    image: nginx:alpine
    volumes:
    - "./data:/usr/share/nginx/html"
    - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    environment:
    - VIRTUAL_HOST
    networks:
    - lb_web
